language: julia
os:
  - linux
  - osx
julia:
  - 0.5
notifications:
  email: false
addons:
  apt:
    packages:
    - liblzma-dev
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("ReadStat")'
  - julia --check-bounds=yes -e 'Pkg.test("ReadStat", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ReadStat")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
